### PR TITLE
Fix Issue #33

### PR DESCRIPTION
**Pull request by adrienbrunet**
As discussed in Issue #33, we had a warning about tether not being available in the console.

I just added the tether folder in assets and added the dependency in layout.html.

I downloaded tether from their website. Not sure what system do you usually use for assets management. npm, bower etc....
I was expecting a package.json, a bower.json or anything. Did not find it.

Hope this is ok. Cheers :beer:

### CODE REVIEW

**Comment by freakboy3742** [comment]
Thanks for the contribution! However, it looks like you've committed a bunch of stuff that isn't required for production - it looks like the full Tether distribution, not just the JS files needed for deployment. 

If possible, could you prune this back to just the files that are needed for production?

Alternatively, if you can suggest a good way to manage these resources using bower (or something similar), I'm open to the suggestion.

**Comment by adrienbrunet** [comment]
Just done that. I'm not used to manage assets that way.
I often just manage a package.json file with all my dependencies. I try to avoid keeping any js package in my repo and add a 'npm install line' in my build process...

What I don't find quite handy keeping only production assets, it tends to be harder to update and manage versions. But I may be missing the full picture here.

**Comment by freakboy3742** [comment]
Certainly understandable; the catch is that Lektor is a static site generator, and doesn't have a build process in that sense (or, at least, not one that is integrated with resource managers like bower or grunt).

As I understand it, this is something that *could* be added as a plugin; it's just not available right now.

**Comment by adrienbrunet** [comment]
Fair enough. My Jekyll blog suffers the same symptoms. =)

**Comment by glasnt** [comment]
It looks like the tether.min.js asset wasn't added in the many changes in this PR. I've added this directly in b18d31545dcb9e071032bf1602929b9ab418514e

**Comment by adrienbrunet** [comment]
That makes me grumpy. How can I fail to add files with git. Grrrr!
Anyway case closed, great work everyone! :+1: Cheeeers

**Pull request merged**
