### PR TITLE
Fixed file extensions

### PR DESCRIPTION
**Pull request by fjeansilva**
I've modified files with extensions Ir (uppercase i) to lr (lowercase L).

### CODE REVIEW

**Comment by goanpeca** [comment]
@fjeansilva thanks, but why did you open a new PR to change the extensions? you should have made these changes in the original PR.

**Comment by goanpeca** [comment]
So can we close this?

**Comment by fjeansilva** [comment]
Hi @goanpeca, i thought that fix should be another branch!! I sended the fix in original branch!! Thanks. I can close this PR?

**Comment by goanpeca** [comment]
Yes I saw, that is why I asked if we could close this, closed :-p !

**Comment by fjeansilva** [comment]
Sorry, I just saw your message after I sent my :)

**Pull request closed without merging**
