### PR TITLE
Created PT_BR translation

### PR DESCRIPTION
**Pull request by AltoRetrato**

### CODE REVIEW

**Comment by AltoRetrato** [comment]
Brazil.

**Comment by goanpeca** [comment]
This page will display all pages with missing translations (some pages refering to users supporting pybee will probably never have a translation, so maybe we can filter those out some day) and on the bottom you see that there are pages that are translated, but maybe outdated (because the original page in english was updated recently)

https://pybee.org/pt_BR/contributing/how/translations/

**Comment by AltoRetrato** [comment]
Thanks. I've been using that link already, and also noticed that the contributors pages really pollute the results... I've also already checked all translatable pages to see which ones I could/should ignore, which ones to prioritize, and to have some idea of how much work is ahead.

**Comment by goanpeca** [comment]
>and also noticed that the contributors pages really pollute the results...

Yes this is something we need to fix, to be more realistic. I will work on something :-)

**Pull request merged**
