### PR TITLE
FOSSKit - Homepage improvements

### PR DESCRIPTION
**Pull request by yelluw**
This pull request contains improvement to the homepage.
The improvements are:

- Headline content is project's USP (Unique Selling Proposition).
- Sub-headline content is the project's elevator pitch.
- Hero buttons change to better direct users to the tutorials, contributing, and donation pages.
- New navigation item `Donate`

### CODE REVIEW

**Comment by yelluw** [comment]
Forgot to mention @freakboy3742 
😀

**Comment by goanpeca** [comment]
Could you post a screenshot :-) ?

**Comment by yelluw** [comment]
I was about to but noticed I broke the build 😄

screen shot 2017-12-09 at 3 07 25 pm

**Comment by goanpeca** [comment]
Hi @yelluw I do not think the error is related to your work. This link

https://pycon-au.org/program/sprints/

Apparently does not work anymore

**Comment by yelluw** [comment]
@goanpeca Yes, you are right. Here I was sweating my first pull request 😅

Who should remove the link?

**Comment by goanpeca** [comment]
We should probably replace by https://2017.pycon-au.org/program/sprints/ ?

**Comment by yelluw** [comment]
Made the updates.

**Comment by yelluw** [comment]
Thank you, @phildini 
Working on some additional stuff next 😉

**Comment by eliasdorneles** [comment]
wow, this is looking niiice!!
Nice work, Pablo!

**Comment by yelluw** [comment]
Thanks @eliasdorneles 
We should have more cool stuff soon 😃

**Comment by phildini** [comment]
Hey @yelluw how are you going to signal when you're ready for merge? Is this ready now?

**Comment by yelluw** [comment]
Oh, I was waiting on your side 😅

Please merge it in. Next round is separate from this. 

Thank you @phildini !

**Comment by yelluw** [comment]
Super pumped!

**Pull request merged**
