### PR TITLE
Translated part of Community to pt_BR

### PR DESCRIPTION
**Pull request by mschonfinkel**
Work in Progress

Translated some of the community to Portuguese.

### CODE REVIEW

**Comment by eliasdorneles** [comment]
Hi @mschonfinkel -- is this ready to be reviewed and merged?

**Comment by mschonfinkel** [comment]
@eliasdorneles Guess I just have to solve this merge conflict.

**Comment by eliasdorneles** [comment]
The build is broken because of some broken links in Batavia docs, which should be fixed by: https://github.com/pybee/batavia/issues/682
As they're unrelated to this PR, I'm merging it.

**Comment by eliasdorneles** [comment]
And thanks @mschonfinkel ! :metal: :smiley: :+1:

**Pull request merged**
