### PR TITLE
PR: Fix broken links and add a script to check these links

### PR DESCRIPTION
**Pull request by goanpeca**
Related to #145 

----

@freakboy3742, @phildini, I created a script to test for broken links (anchors and images) based on the built site. I had to update templates to avoid hardcoding images and update models to include extra fields reffering to logo/images

The output of the script is something like:

```
$ python scripts/check_links.py

Running Lektor Server:
	$ lektor server --no-prune --port 5000 --output-path /var/folders/t2/h1vy0xx52hb5x5xq0xhch4lw0000gn/T/tmpPzO96f


Building static site:

...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished building site!



Finding built files:

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Parsing built files for links:

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Found 2189 unique links!


Checking links

................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Error number: 0
Status code or error type: 404
http://127.0.0.1:5000/contributing/first-time/what-is-a/package-manager
-----------------------------------------------------------------------
	http://127.0.0.1:5000/pt_BR/contributing/how/first-time/setup


..............................

Error number: 1
Status code or error type: 404
http://127.0.0.1:5000/dco/
--------------------------
	http://127.0.0.1:5000/pt_BR/contributing/how/process
	http://127.0.0.1:5000/zh_TW/contributing/how/process


............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Error number: 2
Status code or error type: ReadTimeout
https://jambonsw.com
--------------------
	http://127.0.0.1:5000/ar_AR/news/buzz/a-request-for-your-help
	http://127.0.0.1:5000/ar_AR/news/buzz
	http://127.0.0.1:5000/de_DE/news/buzz/a-request-for-your-help
	http://127.0.0.1:5000/de_DE/news/buzz
	http://127.0.0.1:5000/es/noticias/zumbido
	http://127.0.0.1:5000/es/noticias/zumbido/una-solicitud-de-ayuda
	http://127.0.0.1:5000/news/buzz/a-request-for-your-help
	http://127.0.0.1:5000/news/buzz
	http://127.0.0.1:5000/pt_BR/news/buzz/a-request-for-your-help
	http://127.0.0.1:5000/pt_BR/news/buzz
	http://127.0.0.1:5000/zh_TW/news/buzz/a-request-for-your-help
	http://127.0.0.1:5000/zh_TW/news/buzz


................................................................................................

3 links are broken!

Process took 406.805313 seconds
```

It would be ideal to be able to run this script as part of the CI checks, beekeeper perhaps? The dependencies are `lektor`, `requests` and `beautifulsoup4`

I have not tested the script it on windows (yet), but I think it should work.

### CODE REVIEW

**Comment by freakboy3742** [comment]
More amazing fixes, @goanpeca - Thanks!

Regarding getting this into CI - I completely agree. Ideally, we'd run the link check on a PR, so we know the links are good prior to merging. It *should* be as simple as putting the calls into a stage in the `.travis.yml` file.

**Comment by goanpeca** [comment]
@freakboy3742 Could we use circleci perhaps? it is much faster than travis I believe.

**Comment by freakboy3742** [comment]
The setup we've got is already on Travis; If we're going to move, we'd be moving to [Beekeeper](https://beekeeper.herokuapp.com) :-)

**Comment by goanpeca** [comment]
>The setup we've got is already on Travis; If we're going to move, we'd be moving to Beekeeper :-)

Right!, ok, I will add the changes to travis then ;-)

**Pull request merged**
