### PR TITLE
DONE 'Project' and 'What is PyBee' tabs translated to pt_BR

### PR DESCRIPTION
**Pull request by jrodolfolima**
One more portion translated to pt_BR

Also corrected README.rst to say lektor also works with Python 3.x

### CODE REVIEW

**Comment by eliasdorneles** [comment]
This PR has overlapping content with #234 and will create conflicts after merging.
You can either incorporate the changes from this one to that one, or remove the overlapping content.

**Comment by jrodolfolima** [comment]
I have no idea whatsoever of how to do either of these things.

Is #234 my own PR?


2017-10-23 19:10 GMT-02:00 Elias Dorneles <notifications@github.com>:

**Comment by eliasdorneles** [comment]
> Is #234 my own PR?

Right, it's your other PR.

No worries, I'll just for you to update that other one (which is in your branch `translate_Projects_tab_pt_BR`, you can just push new commits and the PR will update automatically) and after that one is merged, we can handle the conflicts if they appear.

**Comment by jrodolfolima** [comment]
OK. Perfect.
Em 23/10/2017 19:25, "Elias Dorneles" <notifications@github.com> escreveu:

**Pull request merged**
