### PR TITLE
Updated PT translation

### PR DESCRIPTION
**Pull request by AltoRetrato**

### CODE REVIEW

**Comment by AltoRetrato** [comment]
I'm a new-bee in this project and still don't know a few things, such as where (and how) some page contents are defined. In the case of [this page](https://pybee.org/pt_BR/project/projects/libraries/colosseum/), the English phrase 'So, why is it called "Colosseum"?' seems to be defined not in the same file as most of the page content, but somewhere else.

Where can I learn more about the syntax and other details of the translation files?

**Comment by goanpeca** [comment]
@AltoRetrato some of the text is not part of the content but part of the templates. To be able to handle those items, we use Databags (se [Lektor Docs](https://www.getlektor.com/docs/api/databags) and [this file](https://github.com/pybee/pybee.github.io/blob/lektor/databags/translate.ini))

To fix those entries you will need to add the corresponding translation on the `[pt]` section

**Comment by goanpeca** [comment]
@AltoRetrato now that you have pointed this, could you help us include this explanation on the translation section of the website https://pybee.org/contributing/how/translations/ ?

**Comment by AltoRetrato** [comment]
Thanks, will do.

**Pull request merged**
